version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WebcamSnaps2Kvs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ggn4cqjnvdza"
s3_prefix = "WebcamSnaps2Kvs"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ApiGatewayRoleName=\"TrafficGuardApiGateway\" SnapsToKvsFunctionRoleName=\"TrafficGuardSnapsToKvs\" Deployment=\"Stage\" KVSStreamName=\"traffic-guard\" KVSRegion=\"eu-central-1\" videoWidth=\"640\" videoHeight=\"480\" Path2FFmpeg=\"/opt/lib/ffmpeg\" CognitoUserPoolArn=\"arn:aws:cognito-idp:eu-central-1:785668202743:userpool/eu-central-1_84Uu2uPF1\""
profile = "default"
