version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WebcamSnaps2Kvs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bnc1lgnamqwf"
s3_prefix = "WebcamSnaps2Kvs"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ApiGatewayRoleName=\"TrafficGuardApiGateway\" SnapsToKvsFunctionRoleName=\"TrafficGuardSnapsToKvs\" Deployment=\"Stage\" URLDataFormat=\"data:image/png;base64,\" KVSStreamName=\"traffic-guard\" KVSRegion=\"eu-central-1\" video_width=\"640\" video_height=\"480\" Path2FFmpeg=\"/opt/lib/ffmpeg\""
